### ISSUE TITLE
`NoSuchElementException` when creating reports with Java records

### ISSUE THREAD

**Issue by McPringle** [alejandro-du/report-ui#35]
```
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143) ~[na:na]
	at org.vaadin.reports.PrintPreviewReport.<init>(PrintPreviewReport.java:97) ~[report-ui-4.0.2.jar:4.0.2]
```

It looks like the `BeanPropertySet` can't handle Java records.

**Comment by McPringle** [comment]
When trying to work around this bug, I created Java beans wrapping Java records. The properties were now recognized but it does not see the getters:

```
Caused by: java.lang.NoSuchMethodException: Property 'fullName' has no getter method in class 'class org.XXXXX.RegistrationsDialog$RegistrationListEntityReportWrapper'
```

But the getters are there:

```java
@SuppressWarnings("ClassCanBeRecord")
private static class RegistrationListEntityReportWrapper {

    private final String fullName;
    private final String date;

    public RegistrationListEntityReportWrapper(@NotNull final String fullName, @NotNull final String date) {
        this.fullName = fullName;
        this.date = date;
    }

    public String getFullName() {
        return fullName;
    }

    public String getDate() {
        return date;
    }
}
```

**Comment by McPringle** [comment]
Very crazy: I got it recognizing the getters by extracting the wrapper bean into its own Java file. But, of course, records still do not work and I don't want to clutter my codebase with dozens of wrapper beans and mapping code.

**Comment by alejandro-du** [comment]
Is this solved?
